# registry.gitlab.com/meltano/meltano:latest is also available in GitLab Registry
ARG MELTANO_IMAGE=meltano/meltano:v2
FROM $MELTANO_IMAGE

WORKDIR /project

# Install any additional requirements
COPY ./requirements.txt .
COPY ./meltano.yml .
RUN pip install -r requirements.txt

# Copy over Meltano project directory
COPY . .
RUN meltano install


# Expose default port used by `meltano ui`
EXPOSE 5000

ENTRYPOINT ["meltano"]
